// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVfB_-b5V1B2MZWaGxCzHP3DlmvY8lsFI',
    appId: '1:40693439088:web:61f574f738b959521eb2b5',
    messagingSenderId: '40693439088',
    projectId: 'donation-app-2895f',
    authDomain: 'donation-app-2895f.firebaseapp.com',
    storageBucket: 'donation-app-2895f.firebasestorage.app',
    measurementId: 'G-780DYGWGQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAg-jF2VzJyS69ghk6Yxt0ZhxNEBeplc4',
    appId: '1:40693439088:android:0a949b70001f83521eb2b5',
    messagingSenderId: '40693439088',
    projectId: 'donation-app-2895f',
    storageBucket: 'donation-app-2895f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsnSgkOEXy_TYPEuyMjtu2n24Elv12KME',
    appId: '1:40693439088:ios:4e788297c6fb1b811eb2b5',
    messagingSenderId: '40693439088',
    projectId: 'donation-app-2895f',
    storageBucket: 'donation-app-2895f.firebasestorage.app',
    iosBundleId: 'com.example.loginDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsnSgkOEXy_TYPEuyMjtu2n24Elv12KME',
    appId: '1:40693439088:ios:4e788297c6fb1b811eb2b5',
    messagingSenderId: '40693439088',
    projectId: 'donation-app-2895f',
    storageBucket: 'donation-app-2895f.firebasestorage.app',
    iosBundleId: 'com.example.loginDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVfB_-b5V1B2MZWaGxCzHP3DlmvY8lsFI',
    appId: '1:40693439088:web:4c3e4ccfc75b6ba91eb2b5',
    messagingSenderId: '40693439088',
    projectId: 'donation-app-2895f',
    authDomain: 'donation-app-2895f.firebaseapp.com',
    storageBucket: 'donation-app-2895f.firebasestorage.app',
    measurementId: 'G-LTZYHBF9NK',
  );
}
